//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutosEstoqueClient.ProdutosEstoqueService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/02", ConfigurationName="ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueServiceV2")]
    public interface IProdutosEstoqueServiceV2
    {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/ConsultarEstoqueRespo" +
            "nse")]
        int ConsultarEstoque(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/ConsultarEstoqueRespo" +
            "nse")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/AdicionarEstoqueRespo" +
            "nse")]
        bool AdicionarEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/AdicionarEstoqueRespo" +
            "nse")]
        System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign, Action = "http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/RemoverEstoqueRespons" +
            "e")]
        bool RemoverEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/02/IProdutosEstoqueServiceV2/RemoverEstoqueRespons" +
            "e")]
        System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string numeroProduto, int quantidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutosEstoqueServiceV2Channel : ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueServiceV2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosEstoqueServiceV2Client : System.ServiceModel.ClientBase<ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueServiceV2>, ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueServiceV2
    {
        
        public ProdutosEstoqueServiceV2Client()
        {
        }
        
        public ProdutosEstoqueServiceV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProdutosEstoqueServiceV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutosEstoqueServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutosEstoqueServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int ConsultarEstoque(string numeroProduto)
        {
            return base.Channel.ConsultarEstoque(numeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string numeroProduto)
        {
            return base.Channel.ConsultarEstoqueAsync(numeroProduto);
        }
        
        public bool AdicionarEstoque(string numeroProduto, int quantidade)
        {
            return base.Channel.AdicionarEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string numeroProduto, int quantidade)
        {
            return base.Channel.AdicionarEstoqueAsync(numeroProduto, quantidade);
        }
        
        public bool RemoverEstoque(string numeroProduto, int quantidade)
        {
            return base.Channel.RemoverEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string numeroProduto, int quantidade)
        {
            return base.Channel.RemoverEstoqueAsync(numeroProduto, quantidade);
        }
    }
}
