//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutosEstoqueClient.ProdutosEstoqueService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoEstoqueData", Namespace="http://schemas.datacontract.org/2004/07/ProdutosEstoque")]
    public partial class ProdutoEstoqueData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescricaoProdutoField;
        
        private int EstoqueProdutoField;
        
        private string NomeProdutoField;
        
        private string NumeroProdutoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoProduto
        {
            get
            {
                return this.DescricaoProdutoField;
            }
            set
            {
                this.DescricaoProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstoqueProduto
        {
            get
            {
                return this.EstoqueProdutoField;
            }
            set
            {
                this.EstoqueProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto
        {
            get
            {
                return this.NomeProdutoField;
            }
            set
            {
                this.NomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProduto
        {
            get
            {
                return this.NumeroProdutoField;
            }
            set
            {
                this.NumeroProdutoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://projetoavaliativo.dm113/01", ConfigurationName="ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService")]
    public interface IProdutosEstoqueService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ListarProdutos", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ListarProdutosResponse")]
        string[] ListarProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ListarProdutos", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ListarProdutosResponse")]
        System.Threading.Tasks.Task<string[]> ListarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/IncluirProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/IncluirProdutoResponse")]
        bool IncluirProduto(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/IncluirProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/IncluirProdutoResponse")]
        System.Threading.Tasks.Task<bool> IncluirProdutoAsync(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverProdutoResponse")]
        bool RemoverProduto(string removeProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverProdutoResponse")]
        System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string removeProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ConsultarEstoqueRespons" +
            "e")]
        int ConsultarEstoque(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ConsultarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/ConsultarEstoqueRespons" +
            "e")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/AdicionarEstoqueRespons" +
            "e")]
        bool AdicionarEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/AdicionarEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/AdicionarEstoqueRespons" +
            "e")]
        System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverEstoqueResponse")]
        bool RemoverEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverEstoque", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/RemoverEstoqueResponse")]
        System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/VerProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/VerProdutoResponse")]
        ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData VerProduto(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/VerProduto", ReplyAction="http://projetoavaliativo.dm113/01/IProdutosEstoqueService/VerProdutoResponse")]
        System.Threading.Tasks.Task<ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData> VerProdutoAsync(string numeroProduto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutosEstoqueServiceChannel : ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosEstoqueServiceClient : System.ServiceModel.ClientBase<ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService>, ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService
    {
        
        public ProdutosEstoqueServiceClient()
        {
        }
        
        public ProdutosEstoqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProdutosEstoqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutosEstoqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProdutosEstoqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string[] ListarProdutos()
        {
            return base.Channel.ListarProdutos();
        }
        
        public System.Threading.Tasks.Task<string[]> ListarProdutosAsync()
        {
            return base.Channel.ListarProdutosAsync();
        }
        
        public bool IncluirProduto(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData)
        {
            return base.Channel.IncluirProduto(produtoEstoqueData);
        }
        
        public System.Threading.Tasks.Task<bool> IncluirProdutoAsync(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData)
        {
            return base.Channel.IncluirProdutoAsync(produtoEstoqueData);
        }
        
        public bool RemoverProduto(string removeProduto)
        {
            return base.Channel.RemoverProduto(removeProduto);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string removeProduto)
        {
            return base.Channel.RemoverProdutoAsync(removeProduto);
        }
        
        public int ConsultarEstoque(string numeroProduto)
        {
            return base.Channel.ConsultarEstoque(numeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string numeroProduto)
        {
            return base.Channel.ConsultarEstoqueAsync(numeroProduto);
        }
        
        public bool AdicionarEstoque(string numeroProduto, int quantidade)
        {
            return base.Channel.AdicionarEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string numeroProduto, int quantidade)
        {
            return base.Channel.AdicionarEstoqueAsync(numeroProduto, quantidade);
        }
        
        public bool RemoverEstoque(string numeroProduto, int quantidade)
        {
            return base.Channel.RemoverEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string numeroProduto, int quantidade)
        {
            return base.Channel.RemoverEstoqueAsync(numeroProduto, quantidade);
        }
        
        public ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData VerProduto(string numeroProduto)
        {
            return base.Channel.VerProduto(numeroProduto);
        }
        
        public System.Threading.Tasks.Task<ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData> VerProdutoAsync(string numeroProduto)
        {
            return base.Channel.VerProdutoAsync(numeroProduto);
        }
    }
}
