//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutosEstoqueClient.ProdutosEstoqueService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoEstoqueData", Namespace="http://schemas.datacontract.org/2004/07/ProdutosEstoque")]
    [System.SerializableAttribute()]
    public partial class ProdutoEstoqueData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstoqueProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroProdutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoProduto {
            get {
                return this.DescricaoProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoProdutoField, value) != true)) {
                    this.DescricaoProdutoField = value;
                    this.RaisePropertyChanged("DescricaoProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstoqueProduto {
            get {
                return this.EstoqueProdutoField;
            }
            set {
                if ((this.EstoqueProdutoField.Equals(value) != true)) {
                    this.EstoqueProdutoField = value;
                    this.RaisePropertyChanged("EstoqueProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto {
            get {
                return this.NomeProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdutoField, value) != true)) {
                    this.NomeProdutoField = value;
                    this.RaisePropertyChanged("NomeProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProduto {
            get {
                return this.NumeroProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroProdutoField, value) != true)) {
                    this.NumeroProdutoField = value;
                    this.RaisePropertyChanged("NumeroProduto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutosEstoqueService.IProdutosEstoqueService")]
    public interface IProdutosEstoqueService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/ListarProdutos", ReplyAction="http://tempuri.org/IProdutosEstoqueService/ListarProdutosResponse")]
        string[] ListarProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/ListarProdutos", ReplyAction="http://tempuri.org/IProdutosEstoqueService/ListarProdutosResponse")]
        System.Threading.Tasks.Task<string[]> ListarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/IncluirProduto", ReplyAction="http://tempuri.org/IProdutosEstoqueService/IncluirProdutoResponse")]
        bool IncluirProduto(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/IncluirProduto", ReplyAction="http://tempuri.org/IProdutosEstoqueService/IncluirProdutoResponse")]
        System.Threading.Tasks.Task<bool> IncluirProdutoAsync(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/RemoverProduto", ReplyAction="http://tempuri.org/IProdutosEstoqueService/RemoverProdutoResponse")]
        bool RemoverProduto(string removeProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/RemoverProduto", ReplyAction="http://tempuri.org/IProdutosEstoqueService/RemoverProdutoResponse")]
        System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string removeProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/ConsultarEstoque", ReplyAction="http://tempuri.org/IProdutosEstoqueService/ConsultarEstoqueResponse")]
        int ConsultarEstoque(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/ConsultarEstoque", ReplyAction="http://tempuri.org/IProdutosEstoqueService/ConsultarEstoqueResponse")]
        System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/AdicionarEstoque", ReplyAction="http://tempuri.org/IProdutosEstoqueService/AdicionarEstoqueResponse")]
        bool AdicionarEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/AdicionarEstoque", ReplyAction="http://tempuri.org/IProdutosEstoqueService/AdicionarEstoqueResponse")]
        System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/RemoverEstoque", ReplyAction="http://tempuri.org/IProdutosEstoqueService/RemoverEstoqueResponse")]
        bool RemoverEstoque(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/RemoverEstoque", ReplyAction="http://tempuri.org/IProdutosEstoqueService/RemoverEstoqueResponse")]
        System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string numeroProduto, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/VerProduto", ReplyAction="http://tempuri.org/IProdutosEstoqueService/VerProdutoResponse")]
        ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData VerProduto(string numeroProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutosEstoqueService/VerProduto", ReplyAction="http://tempuri.org/IProdutosEstoqueService/VerProdutoResponse")]
        System.Threading.Tasks.Task<ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData> VerProdutoAsync(string numeroProduto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutosEstoqueServiceChannel : ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosEstoqueServiceClient : System.ServiceModel.ClientBase<ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService>, ProdutosEstoqueClient.ProdutosEstoqueService.IProdutosEstoqueService {
        
        public ProdutosEstoqueServiceClient() {
        }
        
        public ProdutosEstoqueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutosEstoqueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosEstoqueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosEstoqueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ListarProdutos() {
            return base.Channel.ListarProdutos();
        }
        
        public System.Threading.Tasks.Task<string[]> ListarProdutosAsync() {
            return base.Channel.ListarProdutosAsync();
        }
        
        public bool IncluirProduto(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData) {
            return base.Channel.IncluirProduto(produtoEstoqueData);
        }
        
        public System.Threading.Tasks.Task<bool> IncluirProdutoAsync(ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData produtoEstoqueData) {
            return base.Channel.IncluirProdutoAsync(produtoEstoqueData);
        }
        
        public bool RemoverProduto(string removeProduto) {
            return base.Channel.RemoverProduto(removeProduto);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverProdutoAsync(string removeProduto) {
            return base.Channel.RemoverProdutoAsync(removeProduto);
        }
        
        public int ConsultarEstoque(string numeroProduto) {
            return base.Channel.ConsultarEstoque(numeroProduto);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarEstoqueAsync(string numeroProduto) {
            return base.Channel.ConsultarEstoqueAsync(numeroProduto);
        }
        
        public bool AdicionarEstoque(string numeroProduto, int quantidade) {
            return base.Channel.AdicionarEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarEstoqueAsync(string numeroProduto, int quantidade) {
            return base.Channel.AdicionarEstoqueAsync(numeroProduto, quantidade);
        }
        
        public bool RemoverEstoque(string numeroProduto, int quantidade) {
            return base.Channel.RemoverEstoque(numeroProduto, quantidade);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverEstoqueAsync(string numeroProduto, int quantidade) {
            return base.Channel.RemoverEstoqueAsync(numeroProduto, quantidade);
        }
        
        public ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData VerProduto(string numeroProduto) {
            return base.Channel.VerProduto(numeroProduto);
        }
        
        public System.Threading.Tasks.Task<ProdutosEstoqueClient.ProdutosEstoqueService.ProdutoEstoqueData> VerProdutoAsync(string numeroProduto) {
            return base.Channel.VerProdutoAsync(numeroProduto);
        }
    }
}
